platform:ios, 8.0

use_frameworks!
inhibit_all_warnings!
target 'CPCollectionViewWheelLayoutSwift_Example' do
  pod 'CPCollectionViewWheelLayoutSwift', :path => '../'
  target 'CPCollectionViewWheelLayoutSwift_Tests' do
    inherit! :search_paths
  end
end
